/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl.tables.records;


import gon.cue.model.ddl.tables.Magnets;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MagnetsRecord extends TableRecordImpl<MagnetsRecord> implements Record5<Long, Date, String, String, Long> {

    private static final long serialVersionUID = -320436142;

    /**
     * Setter for <code>PUBLIC.MAGNETS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.MAGNETS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.MAGNETS.ADDED</code>.
     */
    public void setAdded(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.MAGNETS.ADDED</code>.
     */
    public Date getAdded() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>PUBLIC.MAGNETS.LINK</code>.
     */
    public void setLink(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.MAGNETS.LINK</code>.
     */
    public String getLink() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.MAGNETS.NAME</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.MAGNETS.NAME</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.MAGNETS.Size</code>.
     */
    public void setSize(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.MAGNETS.Size</code>.
     */
    public Long getSize() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Date, String, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Date, String, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Magnets.MAGNETS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return Magnets.MAGNETS.ADDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Magnets.MAGNETS.LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Magnets.MAGNETS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Magnets.MAGNETS.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getAdded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getAdded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MagnetsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MagnetsRecord value2(Date value) {
        setAdded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MagnetsRecord value3(String value) {
        setLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MagnetsRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MagnetsRecord value5(Long value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MagnetsRecord values(Long value1, Date value2, String value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MagnetsRecord
     */
    public MagnetsRecord() {
        super(Magnets.MAGNETS);
    }

    /**
     * Create a detached, initialised MagnetsRecord
     */
    public MagnetsRecord(Long id, Date added, String link, String name, Long size) {
        super(Magnets.MAGNETS);

        set(0, id);
        set(1, added);
        set(2, link);
        set(3, name);
        set(4, size);
    }
}
